apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecowalk-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecowalk-api
  template:
    metadata:
      labels:
        app: ecowalk-api
    spec:
      containers:
      - name: ecowalk-container
        image: tuongndb1609/ecowalk-backend:v1 # Image bạn vừa push ở Bước 1
        ports:
        - containerPort: 8081 # Port mà ứng dụng của bạn lắng nghe
