apiVersion: v1
kind: Service
metadata:
  name: ecowalk-backend-service
spec:
  selector:
    app: ecowalk-api # Phải khớp với label trong file Deployment của bạn
  ports:
    - protocol: TCP
      port: 80        # Port công khai (người dùng sẽ truy cập qua port 80)
      targetPort: 8081 # Port mà ứng dụng của bạn đang lắng nghe
  type: LoadBalancer  # Yêu cầu AWS tạo một Classic Load Balancer
