name: CI - Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }}

      - name: Update K8s Manifest
        run: |
          cd K8s
          sed -i "s|image: .*todo-frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }}|g" frontend.yml
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          if [[ -n $(git status -s) ]]; then
            git add frontend.yml
            git commit -m "Deploy: Update Frontend image to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi
      - name: Trigger Tekton CD Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "ref": "main",
              "repository": {"url": "'"${{ secrets.REPO_URL }}"'"},
              "service_name": "frontend",
              "action": "build-deploy"
            }'
