name: CI - Frontend Service

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  test-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Trigger Tekton Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "repository": { "url": "${{ github.event.repository.clone_url }}" },
              "ref": "main",
              "sha": "${{ github.sha }}",
              "service_dir": "frontend",
              "manifest_file": "K8s/frontend.yml",
              "image_repo": "harbor.harbor.svc.cluster.local/prod/frontend"
            }'
