name: CI - Stats Service

on:
  push:
    branches: ["main"]
    paths:
      - "backend/stats-service/**"



jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test
        working-directory: backend/stats-service

  security-scan:
    name: Security & Lint Scan
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [super-linter, trivy]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        if: matrix.tool == 'super-linter'
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          FILTER_REGEX_INCLUDE: .*backend/stats-service/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy Scan
        if: matrix.tool == 'trivy'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'frontend' 
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

  trigger:
    needs: security-scan 
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Tekton Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "repository": { "url": "${{ github.event.repository.clone_url }}" },
              "ref": "main",
              "sha": "${{ github.sha }}",
              "service_dir": "backend/stats-service",
              "manifest_file": "K8s/stats.yml",
              "image_repo": "k8s-harbor-harbor-e23646dd89-000fac67939de240.elb.us-east-1.amazonaws.com/prod/stats-service"
            }'
