name: CI - Stats Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/stats-service/**"

jobs:
  build-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/stats-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-backend-stats:${{ github.sha }}

      - name: Update K8s Manifest
        run: |
          cd K8s
          sed -i "s|image: .*todo-backend-stats:.*|image: ${{ secrets.DOCKER_USERNAME }}/todo-backend-stats:${{ github.sha }}|g" stats.yml
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          if [[ -n $(git status -s) ]]; then
            git add stats.yml
            git commit -m "Deploy: Update Stats Service image to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi
      - name: Trigger Tekton CD Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "ref": "main",
              "repository": {"url":"${{ secrets.REPO_URL }}},
              "service_name": "stats",
              "action": "build-deploy"
            }'