name: CI - Todos Service

on:
  push:
    branches: ["main"]
    paths:
      - "backend/todos/**"

jobs:
  test-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- Step 1: Run Tests (The 'CI' part) ---
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests
        run: mvn test
        working-directory: backend/todos

      # --- Step 2: Trigger Tekton Build (The 'CD' part) ---
      - name: Trigger Tekton Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "repository": { "url": "${{ github.event.repository.clone_url }}" },
              "ref": "main",
              "sha": "${{ github.sha }}",
              "service_dir": "backend/todos",
              "manifest_file": "K8s/todos.yml",
              "image_repo": "k8s-harbor-harbor-e23646dd89-000fac67939de240.elb.us-east-1.amazonaws.com:80/prod/todo-service"
            }'
