name: CI - Users Service

on:
  push:
    branches: ["main"]
    paths:
      - "backend/user-service/**"

jobs:
  test-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build and Run Tests
        run: mvn test
        working-directory: backend/user-service

      - name: Trigger Tekton Pipeline
        run: |
          curl -X POST http://${{ secrets.TEKTON_EL_URL }} \
            -H 'Content-Type: application/json' \
            -d '{"repository": { "url": "https://github.com/thanhtai2703/Deploy-Application-to-AWS-EKS.git" }, "commit_sha": "${{ github.sha }}", "branch": "main", "service_name": "users", "context_dir": "backend/user-service", "manifest_file": "K8s/users.yml", "image_repo": "user-service" }'
